<template>
    <div>
        <p>SE LEVANTA LA PRESENTE ACTA, PARA HACER CONSTAR LA SUSTITUCIÓN DE COMPONENTES POR FIN DE VIDA UTIL/REUBICACIÓN/ACONDICIONAMIENTO,
        REALIZADO AL EQUIPO DE CONTROL DE TRANSITO DEL CARRIL A17 EN LA PLAZA DE COBRO No. 001, TLALPAN PERTENECIENTE A LA UNIDA REGIONAL CUERNAVACA.
        </p>
        <p>
        EN LA CIUDAD DE MEXIC0, SIEND0 LAS 18:00 HRS. DEL DÍA 10 DICIEMBRE DEL 2021, EL TNG.OSCAR RAMIREZ LICEA,
        ADMINISTRADOR DE LA PLAZA DE COBRO, Y EL ING. EMMANUEL BRAVO GARCIA TÉCNICo REPRESENTANTE DE LA EMPRESA PRESTADORA
        DE SERVICIOS PROYECTOS Y SERVICIOS INFORMATICOS S.A. DE C.v. Y LOS C. JESUS VENTURA MORENO Y C. ALVARO PEÑA
        HERRERA TESTIGOS DE ASISTENCIA, PARA HACER CONSTAR LA SUuSTITUCION DE COMPONENTES DEL. EQUIPO DEL CARRIL A17 DE
        ACUERDO A LA SOLICITUD URC-SOC-2314-202 DE FECHA 07 DE DICIEMBRE DEL 2021 Y AUrORIZADA EN oFICIO DO/3741/2021, 
        DE FECHA 09 DE DICIEMBRE DE 2021 POR LA GERENCIA DE MANTENIMIENTO Y MODERN1ZACIÓN DE EQUIPOS DE PEAJE: PARA CUYO
        EFECTÓ FUE NECESARIO REPONER EN FECHA 0 DE DICIEMBRE 2021 LAS PARTES QUE A CONTINUACIÓN SE DETALLAN
        </p>
        <p>
        LOS EQUIPOS/cOMPONENT ES DAÑADOS EL ADMINISAXADOR BEDERA IDENTIFICAR Y BMBALAR, ENVIANDOLOS EN UN PERÍopo DE 5 DÍAS
        MAX IMO AL ÄLMACÉN DE LA DELEGACIÓN REGIONAL/GERENCIA DE TRAMO POR OFICIO, PARA su DESTINO FINAL CONEORME LA NORMA
        CAPUFE.
        </p>
        <p>
        LOS TRABAJOS, INSTALACIÓN Y OPERACIÓN DE LA PLAZA DE COBRO QUEDAN A ENTERA SATISFACcczÓN DEL ADMINISTRADOR DE LA
        PLAZA DE COBRO Y/O ENCARGADO DE TURNO.
        </p>
    </div>
</template>

<script>
    export default {
        
    }
</script>
